version: '3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  python:
    image: py-python
    build:
      context: ./python
    container_name: py-python
    working_dir: /web
    volumes:
    - ../web:/web
#    - ../.env:/web/.env
    tty: true
    networks:
      - frontend
      - backend

  nginx:
    image: py-nginx
    build:
      context: ./nginx
    container_name: py-nginx
    working_dir: /web
    depends_on:
      - python
    ports:
    - 80:80
    - 443:443
    networks:
      - frontend

  mysql:
    image: py-mysql
    build:
      context: ./mysql
    container_name: py-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    networks:
      - backend
